version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: publications_db
    ports:
      - "3307:3306"
    volumes:
      - ./init_db.sql:/init_db.sql